## Introduction to Numpy library by Mohammad_Kahkeshani
### you con reach this file  in my github:
### https://github.com/mkahkeshani/ML_Course

In [1]:
import numpy as np

In [2]:
# make an array
a = np.array([1,2,3]) # take a look to syntax
a

array([1, 2, 3])

## some attributes that we use...

In [3]:
a.shape # length of array

(3,)

In [4]:
a.ndim # dimension of array

1

In [5]:
a.dtype # types of elements in array

dtype('int32')

In [6]:
a.size # count of array

3

## 2D array

In [7]:
b =np.array([[1,2,3],[4,5,6]]) # we use vectors to create a 2D array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
b.ndim

2

In [10]:
b.dtype

dtype('int32')

In [11]:
b.size

6

# نکته مهم: تایپ تمام عناصر باید به یک شکل باشد

In [12]:
c =np.array([[1,2.2,3],[4,5,6]]) # we use vectors to create a 2D array
c

array([[1. , 2.2, 3. ],
       [4. , 5. , 6. ]])

In [13]:
c.dtype

dtype('float64')

## Multy array

In [14]:
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[7,8,9],[10,11,12]])

f = np.array([d,e])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
f.shape # tow of 2*3 array

(2, 2, 3)

## بررسی متد های مهم

## Arange

In [16]:
g = np.arange(0,21,2) # a range like python list
g

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Linspace

In [17]:
h = np.linspace(0, 20, 5) # a range of numbers with certain step
h

array([ 0.,  5., 10., 15., 20.])

## Ones

In [18]:
i = np.ones([3,4]) # create ones array by your own shape 
i

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Zeros

In [19]:
j = np.zeros([3,4]) # create zero array by your own shape 
j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Note: we have ones_like and zeros_like geuss what are them?

## Random

In [20]:
k = np.random.random((3,4)) 
k

array([[0.6888879 , 0.42249808, 0.46496514, 0.04136023],
       [0.56451633, 0.48306745, 0.80913695, 0.47419907],
       [0.19902306, 0.39610411, 0.08841536, 0.33024555]])

In [21]:
l = np.random.randint(1, 10, (4,2))
l

array([[6, 9],
       [5, 3],
       [7, 1],
       [1, 7]])

In [22]:
m = np.random.rand(30) # give you nymbers between 0 ti 1
m

array([0.19336235, 0.25966057, 0.04735067, 0.68563628, 0.0323263 ,
       0.20197488, 0.6820813 , 0.67419388, 0.97118134, 0.4141515 ,
       0.68370916, 0.9453159 , 0.90276796, 0.40814481, 0.6945787 ,
       0.21670517, 0.03440929, 0.57350817, 0.46052506, 0.6028141 ,
       0.54635732, 0.06478893, 0.48129303, 0.14460795, 0.93708385,
       0.42210518, 0.91232594, 0.58416136, 0.8178364 , 0.81570517])

## Seed

In [23]:
np.random.seed(1) # unchaneable random
n = np.random.randint(1,9,(4,3))
n

array([[6, 4, 5],
       [1, 8, 2],
       [4, 6, 8],
       [1, 1, 2]])

## تغییر شکل یک آرایه  و دسترسی به مقادیر

In [24]:
o = np.arange(1,21)
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
o.shape =(4,5) # change the shape
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
o[1] # indexing

array([ 6,  7,  8,  9, 10])

In [27]:
o[1][2] # or o[1,2]

8

In [45]:
o.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## Numpy Broadcasting

In [28]:
p = np.arange(5)
p

array([0, 1, 2, 3, 4])

In [29]:
p + 4 # broadcast a scaler to a biggest array

array([4, 5, 6, 7, 8])

In [30]:
q = np.random.randint(1,9, size = 5)
q

array([5, 8, 6, 5, 7])

In [31]:
p + q

array([ 5,  9,  8,  8, 11])

In [32]:
p - q

array([-5, -7, -4, -2, -3])

In [33]:
p * q

array([ 0,  8, 12, 15, 28])

In [34]:
p / q

array([0.        , 0.125     , 0.33333333, 0.6       , 0.57142857])

In [35]:
p % q

array([0, 1, 2, 3, 4])

In [36]:
p // q

array([0, 0, 0, 0, 0])

## Add elements

In [37]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
s = np.append(r,[10, 12]) # append element in the end of array
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])